
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1.03 EDK_K_SP3.6
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_OPB_MDM_0_DEVICE_ID,
		XPAR_OPB_MDM_0_BASEADDR,
		XPAR_OPB_MDM_0_BAUDRATE,
		XPAR_OPB_MDM_0_USE_PARITY,
		XPAR_OPB_MDM_0_ODD_PARITY,
		XPAR_OPB_MDM_0_DATA_BITS
	}
};


