
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1.03 EDK_K_SP3.6
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/

#define STDIN_BASEADDRESS 0x10000000
#define STDOUT_BASEADDRESS 0x10000000

/******************************************************************/


/* Definitions for peripheral PLB_BRAM_IF_CNTLR_1 */
#define XPAR_PLB_BRAM_IF_CNTLR_1_BASEADDR 0x00000000
#define XPAR_PLB_BRAM_IF_CNTLR_1_HIGHADDR 0x00003fff


/******************************************************************/

/* Definitions for driver OPBARB */
#define XPAR_XOPBARB_NUM_INSTANCES 1

/* Definitions for peripheral OPB_V20_0 */
#define XPAR_OPB_V20_0_BASEADDR 0xFFFFFFFF
#define XPAR_OPB_V20_0_HIGHADDR 0x00000000
#define XPAR_OPB_V20_0_DEVICE_ID 0
#define XPAR_OPB_V20_0_NUM_MASTERS 1


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral OPB_MDM_0 */
#define XPAR_OPB_MDM_0_BASEADDR 0x10000000
#define XPAR_OPB_MDM_0_HIGHADDR 0x1000FFFF
#define XPAR_OPB_MDM_0_DEVICE_ID 0
#define XPAR_OPB_MDM_0_BAUDRATE 0
#define XPAR_OPB_MDM_0_USE_PARITY 0
#define XPAR_OPB_MDM_0_ODD_PARITY 0
#define XPAR_OPB_MDM_0_DATA_BITS 0


/******************************************************************/


/* Canonical definitions for peripheral OPB_MDM_0 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_OPB_MDM_0_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x10000000
#define XPAR_UARTLITE_0_HIGHADDR 0x1000FFFF
#define XPAR_UARTLITE_0_BAUDRATE 0
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 0
#define XPAR_UARTLITE_0_SIO_CHAN -1


/******************************************************************/


/* Definitions for peripheral FTL_0 */


/* Definitions for peripheral DOCM_CNTLR */
#define XPAR_DOCM_CNTLR_BASEADDR 0x80000000
#define XPAR_DOCM_CNTLR_HIGHADDR 0x80003FFF


/* Definitions for peripheral IOCM_CNTLR */
#define XPAR_IOCM_CNTLR_BASEADDR 0xFFFFC000
#define XPAR_IOCM_CNTLR_HIGHADDR 0xFFFFFFFF


/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_PPC405_ID 0
#define XPAR_PPC405_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_PPC405_ISOCM_DCR_BASEADDR 0x00000010
#define XPAR_PPC405_ISOCM_DCR_HIGHADDR 0x00000013
#define XPAR_PPC405_DSOCM_DCR_BASEADDR 0x00000020
#define XPAR_PPC405_DSOCM_DCR_HIGHADDR 0x00000023
#define XPAR_PPC405_DISABLE_OPERAND_FORWARDING 1
#define XPAR_PPC405_DETERMINISTIC_MULT 0
#define XPAR_PPC405_MMU_ENABLE 1
#define XPAR_PPC405_DCR_RESYNC 0
#define XPAR_PPC405_HW_VER "2.00.c"

/******************************************************************/

