#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/home/kfleming/bluessdTestRig/src/bsv-libraries/modules/bsv-libraries/bluespec/PLB/test/PLBDriver/projects/PLBTestDriver/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /home/kfleming/xilinx/10.1/EDK
NON_CYG_XILINX_EDK_DIR = /home/kfleming/xilinx/10.1/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex2p

DEVICE = xc2vp30ff896-7

LANGUAGE = verilog

SEARCHPATHOPT = 

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

MANAGE_FASTRT_OPTIONS = -reduce_fanout no

OBSERVE_PAR_OPTIONS = -error no

TESTAPP_MEMORY_OUTPUT_DIR = TestApp_Memory
TESTAPP_MEMORY_OUTPUT = $(TESTAPP_MEMORY_OUTPUT_DIR)/executable.elf

TESTAPP_FTL_OUTPUT_DIR = TestApp_FTL
TESTAPP_FTL_OUTPUT = $(TESTAPP_FTL_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

PLB_PPC405_0_BOOTLOOP = $(BOOTLOOP_DIR)/plb_ppc405_0.elf

PLB_PPC405_1_BOOTLOOP = $(BOOTLOOP_DIR)/plb_ppc405_1.elf

BRAMINIT_ELF_FILES =  $(TESTAPP_FTL_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe plb_ppc405_0 $(TESTAPP_FTL_OUTPUT) 

ALL_USER_ELF_FILES = $(TESTAPP_MEMORY_OUTPUT) $(TESTAPP_FTL_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti


LIBRARIES =  \
       plb_ppc405_0/lib/libxil.a  \
       plb_ppc405_1/lib/libxil.a 
VPEXEC = virtualplatform/vpexec

LIBSCLEAN_TARGETS = plb_ppc405_0_libsclean plb_ppc405_1_libsclean 

PROGRAMCLEAN_TARGETS = TestApp_Memory_programclean TestApp_FTL_programclean 

CORE_STATE_DEVELOPMENT_FILES = 

WRAPPER_NGC_FILES = implementation/plb_ppc405_0_wrapper.ngc \
implementation/plb_ppc405_1_wrapper.ngc \
implementation/plb_reset_block_wrapper.ngc \
implementation/plb_iocm_wrapper.ngc \
implementation/plb_iocm_cntlr_wrapper.ngc \
implementation/plb_isocm_bram_wrapper.ngc \
implementation/plb_docm_wrapper.ngc \
implementation/plb_docm_cntlr_wrapper.ngc \
implementation/plb_dsocm_bram_wrapper.ngc \
implementation/plb_plb_wrapper.ngc \
implementation/plb_plb_bram_if_cntlr_1_wrapper.ngc \
implementation/plb_plb_bram_if_cntlr_1_bram_wrapper.ngc \
implementation/plb_dcm_0_wrapper.ngc \
implementation/plb_plb2opb_bridge_0_wrapper.ngc \
implementation/plb_opb_v20_0_wrapper.ngc \
implementation/plb_opb_mdm_0_wrapper.ngc \
implementation/plb_ftl_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION TESTAPP_MEMORY
#################################################################

TESTAPP_MEMORY_SOURCES = TestApp_Memory/src/TestApp_Memory.c 

TESTAPP_MEMORY_HEADERS = 

TESTAPP_MEMORY_CC = powerpc-eabi-gcc
TESTAPP_MEMORY_CC_SIZE = powerpc-eabi-size
TESTAPP_MEMORY_CC_OPT = -O2
TESTAPP_MEMORY_CFLAGS = 
TESTAPP_MEMORY_CC_SEARCH = # -B
TESTAPP_MEMORY_LIBPATH = -L./plb_ppc405_0/lib/ # -L
TESTAPP_MEMORY_INCLUDES = -I./plb_ppc405_0/include/ # -I
TESTAPP_MEMORY_LFLAGS = # -l
TESTAPP_MEMORY_LINKER_SCRIPT = TestApp_Memory/src/TestApp_Memory_LinkScr.ld
TESTAPP_MEMORY_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(TESTAPP_MEMORY_LINKER_SCRIPT) 
TESTAPP_MEMORY_CC_DEBUG_FLAG =  -g 
TESTAPP_MEMORY_CC_PROFILE_FLAG = # -pg
TESTAPP_MEMORY_CC_GLOBPTR_FLAG= # -msdata=eabi
TESTAPP_MEMORY_CC_INFERRED_FLAGS= 
TESTAPP_MEMORY_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_START_ADDR=
TESTAPP_MEMORY_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
TESTAPP_MEMORY_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
TESTAPP_MEMORY_OTHER_CC_FLAGS= $(TESTAPP_MEMORY_CC_GLOBPTR_FLAG)  \
                  $(TESTAPP_MEMORY_CC_START_ADDR_FLAG) $(TESTAPP_MEMORY_CC_STACK_SIZE_FLAG) $(TESTAPP_MEMORY_CC_HEAP_SIZE_FLAG)  \
                  $(TESTAPP_MEMORY_CC_INFERRED_FLAGS)  \
                  $(TESTAPP_MEMORY_LINKER_SCRIPT_FLAG) $(TESTAPP_MEMORY_CC_DEBUG_FLAG) $(TESTAPP_MEMORY_CC_PROFILE_FLAG) 

#################################################################
# SOFTWARE APPLICATION TESTAPP_FTL
#################################################################

TESTAPP_FTL_SOURCES = TestApp_FTL/src/TestApp_Memory.c 

TESTAPP_FTL_HEADERS = 

TESTAPP_FTL_CC = powerpc-eabi-gcc
TESTAPP_FTL_CC_SIZE = powerpc-eabi-size
TESTAPP_FTL_CC_OPT = -O2
TESTAPP_FTL_CFLAGS = 
TESTAPP_FTL_CC_SEARCH = # -B
TESTAPP_FTL_LIBPATH = -L./plb_ppc405_0/lib/ # -L
TESTAPP_FTL_INCLUDES = -I./plb_ppc405_0/include/ # -I
TESTAPP_FTL_LFLAGS = # -l
TESTAPP_FTL_LINKER_SCRIPT = TestApp_FTL/TestApp_FTL_linker_script.ld
TESTAPP_FTL_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(TESTAPP_FTL_LINKER_SCRIPT) 
TESTAPP_FTL_CC_DEBUG_FLAG =  -g 
TESTAPP_FTL_CC_PROFILE_FLAG = # -pg
TESTAPP_FTL_CC_GLOBPTR_FLAG= # -msdata=eabi
TESTAPP_FTL_CC_INFERRED_FLAGS= 
TESTAPP_FTL_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_START_ADDR=
TESTAPP_FTL_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
TESTAPP_FTL_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
TESTAPP_FTL_OTHER_CC_FLAGS= $(TESTAPP_FTL_CC_GLOBPTR_FLAG)  \
                  $(TESTAPP_FTL_CC_START_ADDR_FLAG) $(TESTAPP_FTL_CC_STACK_SIZE_FLAG) $(TESTAPP_FTL_CC_HEAP_SIZE_FLAG)  \
                  $(TESTAPP_FTL_CC_INFERRED_FLAGS)  \
                  $(TESTAPP_FTL_LINKER_SCRIPT_FLAG) $(TESTAPP_FTL_CC_DEBUG_FLAG) $(TESTAPP_FTL_CC_PROFILE_FLAG) 
